title: Makerspace Partheland
subtitle: die Mitmachwerkstatt
description: die Mitmachwerkstatt
url: https://makerspace-partheland.de
theme: minimal-mistakes-jekyll

markdown: kramdown
permalink: /:path/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

minimal_mistakes_skin: air
logo: /assets/images/logo.png

collections:
  projects:
    output: true
    permalink: /projekte/:name/
  events:
    output: true
    permalink: /termine/:name/

sass:
  quiet_deps: true


