title: Makerspace Partheland
subtitle: die Mitmachwerkstatt
description: die Mitmachwerkstatt
url: https://makerspace-partheland.de
theme: bulma-clean-theme

markdown: kramdown
permalink: /:path/
locale: de
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

## minimal-mistakes spezifische Optionen vorerst deaktiviert
# minimal_mistakes_skin: air
# Deaktiviert Bild-Logo in der Navbar, damit nicht doppelt gebrandet wird
# logo:

collections:
  projects:
    output: true
    permalink: /projekte/:name/
  events:
    output: true
    permalink: /termine/:name/

sass:
  quiet_deps: true


## Minimal Mistakes Defaults vorerst deaktiviert
# defaults:
#   - scope:
#       path: ""
#       type: pages
#     values:
#       classes: wide
#   - scope:
#       path: ""
#       type: posts
#     values:
#       classes: wide
#   - scope:
#       path: ""
#       type: projects
#     values:
#       classes: wide
#   - scope:
#       path: ""
#       type: events
#     values:
#       layout: default
#       show_date: false
#       classes: wide

