title: Makerspace Partheland
subtitle: die Mitmachwerkstatt
description: "Makerspace Partheland - die Mitmachwerkstatt im Partheland."
url: https://makerspace-partheland.de
theme: bulma-clean-theme

markdown: kramdown
permalink: /:path/
lang: de
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Bulma Clean Theme Optionen (Navigation/Branding)
fixed_navbar: top
force_theme: 
hide_share_buttons: true 

## minimal-mistakes spezifische Optionen vorerst deaktiviert
# minimal_mistakes_skin: air
# Deaktiviert Bild-Logo in der Navbar, damit nicht doppelt gebrandet wird
# logo:

# Cookie-Banner deaktiviert - nur technisch notwendige Cloudflare Cookies

collections:
  projects:
    output: true
    permalink: /projekte/:name/
  events:
    output: true
    permalink: /termine/:name/

future: true

sass:
  quiet_deps: true

exclude:
  - jekyll-env/
  - vendor/
  - start-jekyll.ps1


defaults:
  - scope:
      path: ""
      type: pages
    values:
      hide_hero: true
  - scope:
      path: ""
      type: events
    values:
      layout: page
      hide_hero: true

