title: Makerspace Partheland
subtitle: die Mitmachwerkstatt
description: "Makerspace Partheland - die Mitmachwerkstatt im Partheland."
url: https://makerspace-partheland.de
theme: bulma-clean-theme

timezone: Europe/Berlin

markdown: kramdown
permalink: /:path/
lang: de

organization:
  name: Makerspace Partheland e.V.
  legal_name: Makerspace Partheland e.V.
  url: https://makerspace-partheland.de
  logo: /favicon.png
  same_as:
    - https://github.com/makerspace-partheland
    - https://t.me/makerspacepartheland
  contact_point:
    contact_type: customer support
    url: /austausch/
  address:
    street_address: August-Bebel-Strasse 12
    postal_code: "04824"
    locality: Beucha
    country: DE

theme_color: "#ffffff"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Bulma Clean Theme Optionen (Navigation/Branding)
fixed_navbar: top
force_theme: 
hide_share_buttons: true 

## minimal-mistakes spezifische Optionen vorerst deaktiviert
# minimal_mistakes_skin: air
# Deaktiviert Bild-Logo in der Navbar, damit nicht doppelt gebrandet wird
# logo:

# Cookie-Banner deaktiviert - nur technisch notwendige Cloudflare Cookies

collections:
  projects:
    output: true
    permalink: /projekte/:name/
  events:
    output: true
    permalink: /termine/:name/

future: true

sass:
  quiet_deps: true

exclude:
  - jekyll-env/
  - vendor/
  - start-jekyll.ps1
  - node_modules/
  - package.json
  - package-lock.json
  - scripts/
  - README-WebP-Optimierung.md
  - nul


defaults:
  - scope:
      path: ""
      type: pages
    values:
      hide_hero: true
  - scope:
      path: ""
      type: events
    values:
      layout: page
      hide_hero: true
      location:
        name: Makerspace Partheland e.V.
        street_address: August-Bebel-Strasse 12
        postal_code: "04824"
        locality: Beucha
        country: DE



